# Generated by Django 4.1.1 on 2022-10-21 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('bank_account_number', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('bank_account', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='totaltransaction',
            fields=[
                ('trans_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('totalsale', models.CharField(max_length=45)),
                ('totalorder', models.CharField(max_length=45)),
                ('date_save', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='usernotebook',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/')),
                ('accountlink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='productitem',
            fields=[
                ('pro_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=45)),
                ('brand', models.CharField(max_length=45)),
                ('pro_desc', models.CharField(blank=True, max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.CharField(blank=True, default='instock', max_length=15)),
                ('approvedstatus', models.CharField(blank=True, default='waiting', max_length=15)),
                ('date_add', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('pro_pic', models.ImageField(blank=True, upload_to='images/')),
                ('id_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ordernotebook',
            fields=[
                ('or_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date_buy', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('or_sale', models.FloatField(default=0.0)),
                ('deli_address', models.CharField(max_length=45)),
                ('payslip_pic', models.ImageField(blank=True, upload_to='payslip/')),
                ('status', models.CharField(default='waiting', max_length=45)),
                ('saveyet', models.CharField(default='notyet', max_length=45)),
                ('bank_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advice.paymentmethod')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advice.productitem')),
                ('u_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
